### ISSUE TITLE
NMEA Streaming over TCP is broken

### ISSUE THREAD

**Issue by ph1l** [SignalK/signalk-java#14] opened 2017-04-26 23:16 UTC
reproduced at commit 41288f745edc24aa706fe507c92ee8890452fc60

It appears that my server is configured to stream NMEA over TCP on port 55557:

```
elektron@signalk:~/signalk-java$ cat conf/signalk-config.json | jq .config.server.server.nmea
{
  "generate0183": true
}
elektron@signalk:~/signalk-java$ cat conf/signalk-config.json | jq .config.server.server.tcp
{
  "nmea": {
    "port": 55557
  },
  "port": 55555
}
```

However, it is not actually doing that:

```
elektron@yoga:~$ telnet signalk 55557
Trying 192.168.122.170...
Connected to signalk.virt.
Escape character is '^]'.
{"self":"urn:mrn:signalk:uuid:554c007a-e2e8-4a2b-be1d-5b8ceb5dc35a","version":"v1.0.0","timestamp":"2017-04-26T23:05:57.029Z"}
Connection closed by foreign host.
```

First of all, the server is sending what is clearly a SignalK message over the NMEA port. Secondly, the connection is getting closed after one message and the following error appears on the console log:
```
16:05:57.028 [nioEventLoopGroup-5-1] INFO  nz.co.fortytwo.signalk.server.NettyServer - Signal K OUTPUT_NMEA Connection over TCP from:/192.168.122.1:39472
java.net.UnknownHostException: /192.168.122.170:55557: Name or service not known
        at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
        at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
        at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
        at java.net.InetAddress.getAllByName0(InetAddress.java:1276)
        at java.net.InetAddress.getAllByName(InetAddress.java:1192)
        at java.net.InetAddress.getAllByName(InetAddress.java:1126)
        at java.net.InetAddress.getByName(InetAddress.java:1076)
        at nz.co.fortytwo.signalk.util.Util.sameNetwork(Util.java:631)
        at nz.co.fortytwo.signalk.server.CamelNettyHandler.getHeaders(CamelNettyHandler.java:112)
        at nz.co.fortytwo.signalk.server.CamelNettyHandler.channelActive(CamelNettyHandler.java:83)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:212)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:198)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelActive(ChannelInboundHandlerAdapter.java:64)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:212)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:198)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelActive(ChannelInboundHandlerAdapter.java:64)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:212)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:198)
        at io.netty.channel.DefaultChannelPipeline.fireChannelActive(DefaultChannelPipeline.java:818)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:454)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.access$100(AbstractChannel.java:378)
        at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:424)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:357)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
        at java.lang.Thread.run(Thread.java:745)
```

The SignalK over TCP service appears to also drop after one message:

```
elektron@yoga:~$ telnet signalk 55555
Trying 192.168.122.170...
Connected to signalk.virt.
Escape character is '^]'.
{"self":"urn:mrn:signalk:uuid:554c007a-e2e8-4a2b-be1d-5b8ceb5dc35a","version":"v1.0.0","timestamp":"2017-04-26T23:09:54.930Z"}
Connection closed by foreign host.
```

**Comment by ph1l** [comment] 2017-04-26 23:18
related to #3

**Comment by rob42** [comment] 2017-04-26 23:49
You are seeing the signalk hello message, which should not be sent to the nmea output.

The exception may be caused by your server dns settings. Try logging on and from the console:
`$ host 192.168.122.170`, which should resolve to the server you are on. Ive also seen similar things when IPV6 addresses are being used, as there seems to be some problems translating.

**Comment by ph1l** [comment] 2017-04-27 00:16
```
elektron@signalk:~/signalk-java$ host 192.168.122.170
170.122.168.192.in-addr.arpa domain name pointer signalk.virt.
```

**Comment by rob42** [comment] 2019-02-04 01:46
Closing as very old and many changes now

**Closed as completed by rob42** 2019-02-04 01:46 UTC
